- OWNERS
https://github.com/project-codeflare/codeflare-common/issues/2
Add OWNERS file so the PRs for this repo can be controlled by OpenShift CI.
> Add OWNERS file for OpenShift CI

- .github/workflows/verify_generated_files.yml
verify-manifests PR check is not necessary for this repository as here we don't generate any manifest.
PR check execution on GitHub
> Remove verify-manifests PR check

- support/mcad.go
N/A
Adding a support function for CFO e2e test adjustment.
To be verified as part of CFO e2e test
> Add GetAppWrapper function

- support/environment.go
Added support for specifying MNIST dataset URL. This property can be used to specified alternative location for MNIST dataset in case of testing on disconnected environment,
N/A
> Add property for MNIST dataset URL

- support/ray.go
N/A
Add RayJobId function to get Ray Job id from CR.
N/A
> Add RayJobId function to get Ray Job id from CR

- github-actions/kind/action.yml
N/A
Raise Ingress version to latest released.
Previous version got broken, probably due to some issue with image change.
Run CodeFlare operator PR checks with this change.
PR verified in https://github.com/project-codeflare/codeflare-operator/actions/runs/7726333166/job/21062401704?pr=457
> Raise KinD Ingress controller version to v1.9.6

- support/environment.go
[RHOAIENG-310](https://issues.redhat.com/browse/RHOAIENG-310)
Add support for providing PyPI connection properties
N/A
> Add support for providing PyPI connection properties

- .github/workflows/verify_generated_files.yml
- .github/workflows/verify_unit_test.yml
- github-actions/kind/action.yml
https://issues.redhat.com/browse/RHOAIENG-2615
Updated versions of all GitHub actions to use Node 20.
N/A
> Update deprecated GitHub actions

- support/kueue.go
Add KueueWorkloads function to be used with gomega Eventually.
> Add KueueWorkloads function to be used with gomega Eventually

- support/defaults.go
[RHOAIENG-6450](https://issues.redhat.com/browse/RHOAIENG-6450)
Current Ray image is quite old, community moved significantly.
Use newer versioned Ray image as default for tests.
> Use newer versioned Ray image as default for tests

- go.mod
- go.sum
- support/client.go
- support/prometheus_api_client.go
- support/test.go
Add function to retrieve OpenShift Prometheus API client.
This client can be used to retrieve OpenShift Prometheus metrics, i.e. GPU utilization.
N/A
> Add function to retrieve OpenShift Prometheus API client

- github-actions/kind/resources/kind.yaml
- github-actions/nvidia-gpu-operator/action.yml
- github-actions/nvidia-gpu-setup/action.yml
[RHOAIENG-9004](https://issues.redhat.com/browse/RHOAIENG-9004)
Adding GitHub actions to setup NVIDIA Container Toolkit and install NVidia operator.
Combining those steps we can provide GPU to KinD cluster.
Combined together with https://github.com/project-codeflare/codeflare-operator/pull/575.
> [RHOAIENG-9004] Add GitHub actions to install NVidia GPU on KinD

- support/prometheus_api_client.go
Passing proxy configuration from system into Prometheus client, to make sure client is using same proxy as system.
> Provide proxy configuration for Prometheus client if set in system

- github-actions/nvidia-gpu-operator/action.yml
- github-actions/nvidia-gpu-operator/resources/time-slicing-config.yaml
[RHOAIENG-9004](https://issues.redhat.com/browse/RHOAIENG-9004)
Adding support for NVidia GPU Time slicing, to allow running tests requiring more GPU or tests in parallel.
For more info see https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/gpu-sharing.html#
N/A
> Add support for NVidia GPU Time slicing

- github-actions/kind-add-user/action.yml
- github-actions/nvidia-gpu-setup/action.yml
N/A
Adjusting cleanup script not to fail in case deleted file is missing.
Installing yq library for NVidia as it is missing in NVidia runner image.
> Fix kind-add-user usage for NVidia image

- support/support.go
Update `TestTimeOutDouble` variable value to increase timeout time
> Update TestTimeOutDouble to increase timeout time

- support/defaults.go
Upgrade RayVersion & CodeFlareSDKVersion to be compatible with RayImage
> Upgrade RayVersion & CodeFlareSDKVersion

- github-actions/kind/action.yml
- github-actions/kind/resources/kind.yaml
[RHOAIENG-13430](https://issues.redhat.com/browse/RHOAIENG-13430)
Add support for dynamic number of worker nodes in KIND config file
> Add support for dynamic worker nodes in KIND config file

- support/batch.go
- support/core.go
N/A
Adding functions to retrieve Job status and to create Secrets.
N/A
> Adding functions for Jobs and Secrets

- github-actions/kind/action.yml
Added extra mounts to fix the e2e gpu tests when worker nodes used.
> fix: e2e gpu test with worker nodes

- support/defaults.go
> Update 3.11 ray images

- github-actions/nvidia-gpu-setup/action.yml
Second attempt to fix issue with GPU image. Tested here: https://github.com/project-codeflare/codeflare-sdk/actions/runs/12035523627
> Fix Nvidia GPU setup

- support/fakeclient.go
- support/pytorchjob.go
- support/pytorchjob_test.go
Moving common PyTorchJob functions from ODH DW repo as part of kfto test structure refactoring.
Unit tests.
> Add common functions for PyTorchJob

- support/core.go
- support/core_test.go
Add functions to retrieve ServiceAccounts.
Required for https://github.com/project-codeflare/codeflare-operator/pull/654
N/A
> Add functions to retrieve ServiceAccounts

- github-actions/nvidia-gpu-setup/action.yml
Add `--parents` flag for creation of ~/.config folder, so the script doesn't fail in case folder already exists.
N/A
> NVidia GPU setup - don't fail if directory exists

- support/defaults.go
Relates to [RHOAIENG-16891](https://issues.redhat.com/browse/RHOAIENG-16891)
Update rayROCM image to v6.2.4
> Update rayROCM image to v6.2.4

- support/defaults.go
Relates to [RHOAIENG-16892](https://issues.redhat.com/browse/RHOAIENG-16892)
Update TrainingROCm Image to v6.2.4
> Update TrainingROCm Image

- github-actions/kind/action.yml
Update the kindest/node image version to the minimal working version for kuberay E2E tests
> update kindest/node image version
