project-codeflare/codeflare-common

support/authentication.go
support/config.go
support/core.go
support/image.go
support/rbac.go

https://github.com/red-hat-data-services/distributed-workloads/issues/23
Add test support functions needed by ODH CFO tests.
N/A

Add ODH CFO test specific support functions

---

support/core.go
support/defaults.go
support/environment.go
support/rbac.go

Common functionality for https://github.com/project-codeflare/codeflare-operator/pull/399
Adding common functionality for Nodes and hostname.
N/A

Add common functions for SDK test

---

support/ocm.go

Adding this function to use when updating machinepool tests for this [pr](https://github.com/project-codeflare/instascale/pull/182)
Addition of a label that returns if a machinepool contains a specified label key.

add: function to return machine pool labels

---

support/namespace.go

Moving namespace supported functions implemented in PR https://github.com/project-codeflare/codeflare-operator/pull/286
Added Namespace functions for Create , Get and Delete with name for OLM upgrade test

Add Namespace support functions

---

README.md
github-actions/kind/action.yml
github-actions/kind/resouces/kind.yaml

Fixes https://github.com/project-codeflare/codeflare-common/issues/18
Create dedicated KinD composite action.
Use new action based on instructions in readme.
Tested in https://github.com/sutaakar/codeflare-operator/actions/runs/7034651607/job/19143190536

Create dedicated KinD composite action

---

support/environment.go
support/ocm.go

[Jira Issue](https://issues.redhat.com/browse/RHOAIENG-802)
- Updated to refer to `ClusterID` instead of `OSDClusterID`
- Added Node Pool functions.
This can be verified in conjuntion with the [E2E here](https://github.com/project-codeflare/codeflare-operator/pull/311), which is currently being updated but requires these functions in order to be tested.

Updating support functions for machine and node pools

---

support/route.go

Verify that Route returns error code different from 503 AND no error is returned.
https://onsi.github.io/gomega/#category-2-making-codeeventuallycode-assertions-on-functions
Because waiting on Route exposed failed in OpenShift CI. With current code there is no way to figure out what is the source of the failure.
N/A

Verify returned error when waiting for Route to be exposed

---

github-actions/kind-export-logs/action.yml
github-actions/kind/action.yml

Related to https://github.com/project-codeflare/codeflare-operator/issues/436
Add additional GitHub action covering export all KinD pod logs.
N/A

Add GitHub action for exporting KinD logs

---

.github/workflows/verify_unit_test.yml
go.mod
go.sum
support/batch_test.go
support/core_test.go
support/environment_test.go
support/events_test.go
support/fakeclient.go
support/image_test.go
support/ingress_test.go
support/machine_test.go
support/ray_test.go
support/route_test.go
support/test.go

Closes https://github.com/project-codeflare/codeflare-operator/issues/239
Added Unit test for the Support Package Applicable Modules 
Added Workflow file to test the Unit tests
RUN - `go test  ./support -v`

Added unitest for support-package

---

support/environment.go

Re-worded logs in `GetClusterType()` function. This change was made as this warning currently suggest that an env var should always need to be set, where in fact there are many scenarios where this is not required.
I.e., The [SDK e2e test](https://github.com/project-codeflare/codeflare-sdk/blob/main/tests/e2e/mnist_raycluster_sdk_test.go) can be ran without specifying the `CLUSTER_TYPE` env var if ran on OpenShift environments.
If a test does require the env var to be set, the test will fail or skip as being done i.e., on InstaScale tests: https://github.com/project-codeflare/codeflare-operator/blob/main/test/e2e/instascale_machinepool_test.go#L33-L36 
PR check is sufficient.

Re-word logs in GetClusterType()

---

github-actions/kind/action.yml
github-actions/kind/resources/kind.yaml

Related to: https://issues.redhat.com/browse/RHOAIENG-2058
- Map Host Port 80 to Container Port 80 in KinD Setup. Required for usage against CodeFlare-SDK e2e test.
- Renamed directory.

[e2e] Add Host to Container port mapping for KinD Cluster

---

github-actions/kind-add-user/action.yml

[RHOAIENG-2632](https://issues.redhat.com/browse/RHOAIENG-2632)
Adding GitHub composite action for adding KinD user.
Verified using own operator repository fork.

GitHub composite action for adding KinD user

---

github-actions/kind-add-user/action.yml

Related to: https://github.com/project-codeflare/codeflare-common/pull/33 
Added `rm ca.srl` to the cleanup as I found it was generated when creating the user locally.
With a KinD cluster named `kind`, I ran the following locally, where the `ca.srl` is now removed on cleanup:
```
docker cp kind-control-plane:/etc/kubernetes/pki/ca.crt .
docker cp kind-control-plane:/etc/kubernetes/pki/ca.key .
openssl genrsa -out user.key 2048
openssl req -new -key user.key -out user.csr -subj '/CN=sdk-user/O=tenant'
openssl x509 -req -in user.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out user.crt -days 360
user_crt=$(base64 --wrap=0 user.crt)
user_key=$(base64 --wrap=0 user.key)
yq eval -i ".contexts += {\"context\": {\"cluster\": \"kind-kind\", \"user\": \"sdk-user\"}, \"name\": \"sdk-user\"}" …
```

Add 'rm ca.srl' to kind-add-user workflow

---

support/rbac.go
support/rbac_test.go

N/A
Added support for binding Users to Roles or ClusterRoles.
N/A

Add user rolebindings

---

support/fakeclient.go
support/kueue.go
support/kueue_test.go

Add function to create a Kueue LocalQueue.

Add functions to create Kueue resources

---

support/kueue.go
support/kueue_test.go

N/A
Added a function to return Kueue Workloads resources and check if Workload is admitted.
N/A

Add function to get Kueue workloads

---

github-actions/kind/action.yml

N/A
Use Dnsmasq to provide DNS wildcard support for KinD deployment used in PR checks.
Use complex hostname to send requests on KinD.
Was tested on https://github.com/project-codeflare/codeflare-operator/pull/520.

Use Dnsmasq to provide DNS for KinD

---

github-actions/kind/action.yml
github-actions/kind/resources/kind.yaml

https://issues.redhat.com/browse/RHOAIENG-7055
Exposing HTTPS endpoint on KinD to be able to test gRPC calls.
N/A

Enable HTTPS for KinD cluster, enable SSL passthrough

---

support/ray_cluster_client.go
support/support.go

- Updated ray job support functions to handle ray job api operations using tls check
- Added functions for asserting ray job status
Manually 

Update ray support functions to handle ray job api operation  using tls check verification for insecure cluster

---

support/image.go
support/image_test.go

https://issues.redhat.com/browse/RHOAIENG-10013 
This PR adds a function for imagestreamtag which is needed for this [change](https://github.com/opendatahub-io/distributed-workloads/pull/214) 

Add function for imagestreamtag

---

Makefile
support/defaults.go

[RHOAIENG-12186](https://issues.redhat.com/browse/RHOAIENG-12186)
Upgrading use of Ray to version to 2.35.0 in makefile and updating default ray image used.

Upgrade Ray to version 2.35.0

---

support/ray_api.go
support/ray_cluster_client.go
support/ray_cluster_client_helper.go

Rewritten `NewRayClusterClient` function to accept only `RayClusterClientConfig` with all the needed configuration.
`RayClusterClientConfig`  allows users to pass `http.Client` with any configuration which user needs, providing configuration flexibility.
Simplified and adjusted client functions to better reflect underlying REST API.
Purpose is to make Ray client flexible enough to allow its usage outside of RHOAI, potentially donating it to Ray community.
Verified by using the new implementation in ODH/DW repo to run integration tests.

Ray cluster client redesign

---

Makefile
support/defaults.go
support/environment.go
support/environment_test.go

Removing CodeFlare SDK version as CodeFlare SDK doesn't use Go lang tests any more. 
Adjusted Makefile to align with current content of defaults.go
N/A
Cleanup of default values and Makefile.
N/A, there should be no functionality change.

Cleanup of codeflare-common defaults and Makefile

---

support/defaults.go
support/environment.go

RHOAIENG-11046 - Add support for AMD GPU image

---

support/defaults.go
support/environment.go

Add support for ray-torch-amd and ray-torch-rocm image

Add support for torch-amd and torch-rocm image

---

support/kueue.go
support/namespace.go
support/test.go

N/A
Making Option and ErrorOption public so they can be used in other projects depending on `codeflare-common`.
N/A

Make Option and ErrorOption public

---

support/environment.go

Make one common env variable for all ray images as it helps to pass the any custom ray image with one environment variable instead of specifying a separate environment variables for different ray images. 
Also with increase in number of accelerators in future, it will keep increasing environment variables.

Make one common env variable for all ray images

---

support/defaults.go
support/environment.go
support/environment_test.go

This issue is related to [RHOAIENG-16035](https://issues.redhat.com/browse/RHOAIENG-16035)
Add support for environment variables for Training images. This change helps in 
- Providing default value of images 
- consistency with the pattern for all other images
- providing one common variable for all Training images 
- [] Testing is not required for this change

Add support for environment variables for Training images

---

support/core.go

Added `PodLog` function to be able to retrieve Pod log for gomega `Eventually` assertions.
Renamed `GetPodLogs` to `GetPodLog` to keep consistency, the previous function is not used anywhere.
N/A

Add PodLog function to retrieve Pod log using function

---

support/accelerator.go

Move accelerator function to codeflare-common support from https://github.com/opendatahub-io/distributed-workloads/blob/main/tests/kfto/support.go 
NA

Move accelerator function to codeflare-common support
